# books/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    AuthViewSet,
    CategoryViewSet,
    BookViewSet,
    AdminDashboardViewSet,
    ProfileViewSet
)

# The router automatically generates the URL patterns for your ViewSets.
router = DefaultRouter()
router.register(r'auth', AuthViewSet, basename='auth')
router.register(r'categories', CategoryViewSet, basename='category')
router.register(r'books', BookViewSet, basename='book')
router.register(r'admin-dashboard', AdminDashboardViewSet, basename='admin-dashboard')

# This line ensures the /api/profile/me/ URL is created.
router.register(r'profile', ProfileViewSet, basename='profile')

# The app's urlpatterns are the URLs generated by the router.
urlpatterns = [
    path('', include(router.urls)),
]
