# Generated by Django 4.2 on 2025-10-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='bookborrow',
            name='purpose',
        ),
    ]
