# Generated by Django 4.2 on 2025-10-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_image_remove_bookborrow_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
