# Generated by Django 4.2 on 2025-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_studentprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sap_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
