# Generated by Django 4.2 on 2025-10-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_image_bookborrow_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
