# Generated by Django 4.2 on 2025-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
