# Generated by Django 4.2 on 2025-10-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_description_book_embedding'),
        ('books', '0006_remove_bookborrow_purpose_and_more'),
    ]

    operations = [
    ]
